services:
  redis:
    image: redis
    container_name: myredis
    ports:
      - "6379:6379"
    networks:
      - rag-network

  chromadb:
    image: chromadb/chroma
    container_name: chromadb
    ports:
      - "8000:8000"
    volumes:
      - chroma-data:/data
    networks:
      - rag-network

  backend:
    build: ./backend
    image: rag-backend-image
    container_name: rag-backend
    ports:
      - "5001:3000"
    env_file:
      - ./backend/.env
    depends_on:
      - redis
      - chromadb
    volumes:
      - ./backend:/app
    networks:
      - rag-network

  frontend:
    build: ./frontend
    image: rag-frontend-image
    container_name: rag-frontend
    ports:
      - "3001:80"
    env_file:
      - ./frontend/.env
    depends_on:
      - backend
    volumes:
      - ./frontend:/app 
    networks:
      - rag-network

volumes:
  chroma-data:
    name: chroma-data

networks:
  rag-network:
    name: rag-network
    driver: bridge
